name: Build and Push Docker Image

on:
  push:
    # Only trigger workflow when these files/directories change
    paths:
      - 'app/**'
      - 'config/**'
      - 'lib/**'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'Dockerfile'
      - '.dockerignore'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout private actions
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MY_GITHUB_USERNAME }}/actions-kit
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: .github/actions

      - name: Get Vault Secrets
        id: vault
        uses: ./.github/actions/.github/actions/vault-secrets
        with:
          vault_addr: "http://${{ secrets.DROPLET_IP }}:8200"
          droplet_ip: ${{ secrets.DROPLET_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.vault.outputs.docker_hub_username }}
          password: ${{ steps.vault.outputs.docker_hub_password }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: |
            ${{ steps.vault.outputs.docker_hub_username }}/${{ steps.vault.outputs.app_name }}-backend:latest
            ${{ steps.vault.outputs.docker_hub_username }}/${{ steps.vault.outputs.app_name }}-backend:${{ github.sha }}
      
      - name: Trigger Deploy workflow in DevOps
        if: success() # only runs if previous steps succeeded
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.MY_GITHUB_USERNAME }}/${{ steps.vault.outputs.devops_repo }}/dispatches \
            -d '{"event_type": "backend-updated", "client_payload": {"customData": "value"}}'